#!/usr/bin/env bash
# Flatten the skill into one self-contained prompt, for agents with no
# progressive disclosure (Codex, Cursor, Gemini CLI, raw API calls).
#
# Usage: scripts/build_portable.sh [output_path]
#        defaults to dist/groundwork.flat.md

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL="$ROOT/skills/groundwork"
OUT="${1:-$ROOT/dist/groundwork.flat.md}"
mkdir -p "$(dirname "$OUT")"

{
  echo "<!-- GENERATED by scripts/build_portable.sh — edit skills/groundwork instead -->"
  echo

  # SKILL.md without the YAML frontmatter, which means nothing to an agent
  # that has no skill loader.
  awk 'BEGIN{n=0} /^---$/{n++; next} n>=2' "$SKILL/SKILL.md"

  echo
  echo "---"
  echo
  echo "# Appendix: reference material"
  echo
  echo "The workflow above refers to these files. They are inlined here because"
  echo "this build targets agents that load their whole instruction set up front."

  for f in "$SKILL"/references/*.md; do
    echo
    echo "<!-- from references/$(basename "$f") -->"
    echo
    sed 's/^#/##/' "$f"   # demote one level, so they nest under the appendix
  done

  echo
  echo "<!-- from templates/RECORD.template.md -->"
  echo
  echo "## The template"
  echo
  echo '```markdown'
  cat "$ROOT/templates/RECORD.template.md"
  echo '```'
} > "$OUT"

WORDS=$(wc -w < "$OUT")
echo "wrote $OUT"
echo "~$WORDS words (~$((WORDS * 4 / 3)) tokens) — this loads on every invocation"
